In [1]:
# file path / directory handling
import os 
import config

# for Google Maps API
import requests

In [2]:
# Data manipulation

# for dataframe for up to 2D data structure
import pandas as pd
# to use sql syntax to talk with pandas dataframe 
from pandasql import sqldf 

"""
# for multi-dimensional data structure analytics 
# can work with pandas for better multi-dimensional data structure  
"""
import numpy as np   

"""
Python Library for Low-Code Data Visualization 
"""
import seaborn as sns
import matplotlib.pyplot as plt


# to display important warning messages from Python
import warnings
warnings.filterwarnings('ignore')

In [44]:
eda_premises = pd.read_csv("C://Users//user//Documents//WQD7002 - FYP//Datasets//lookup_premise_geocoded.csv")
dirty_eda_premises = pd.read_csv("C://Users//user//Documents//WQD7002 - FYP//Datasets//lookup_premise_geocode_challege.csv")

In [45]:
eda_premises.head()

,premise_code,premise,address,premise_type,state,district,latitude,longitude
0,-1,NaN,",",NaN,NaN,NaN,NaN,NaN
1,2,PASAR BESAR IPOH,"JALAN LAKSAMANA,TAMAN JUBILEE,30300 IPOH, PERAK",Pasar Basah,Perak,Kinta,4.592759,101.083988
2,3,JUSCO AYER KEROH,"LOT 4991,MUKIM BUKIT BARU,75450 LEBUH AYER KER...",Pasar Raya / Supermarket,Melaka,Melaka Tengah,2.242987,102.290511
3,6,KEDAI RUNCIT TAFAZ MAJU PRESINT 9,"NO.5, JALAN P9B/1,PRESINT 9,62250 PUTRAJAYA",Kedai Runcit,W.P. Putrajaya,Wp Putrajaya,2.944309,101.675805
4,7,KEDAI RUNCIT SYAZ MAJU PRESINT 9,"NO.5, JALAN P9E/1,PRESINT 9,62250 PUTRAJAYA",Kedai Runcit,W.P. Putrajaya,Wp Putrajaya,2.941244,101.675183

In [46]:
eda_premises.tail()

,premise_code,premise,address,premise_type,state,district,latitude,longitude
2705,20899,PASARAYA MADEENA FROZEN & FRESH MART,"NO.67, JALAN 3/76,,DESA PANDAN,",Pasar Mini,W.P. Kuala Lumpur,Titiwangsa,3.147010,101.737343
2706,20900,LU MIAO,"NO.9, JALAN WAWASAN JAYA,TAMAN WAWASAN 1, TANJ...",Pasar Mini,Pahang,Rompin,2.798548,103.485467
2707,20901,S.NISAH BIVI,"PT 5740,JLN T.S 2/1 E,,TMN SEMARAK 2,NILAI, N.S.",Pasar Mini,Negeri Sembilan,Seremban,2.821091,101.817199
2708,20902,JAYA 33 SUPERMARKET,"PG-01, JAYA 33, NO 3 JALAN SEMANGAT, SECTION 1...",Pasar Raya / Supermarket,Selangor,Petaling Jaya,3.110393,101.636942
2709,20903,PASARAYA HM (HOCK MEI TRADING SDN BHD),"NO 1, BLOCK B,C &D, JALAN PJS 3/2,PETALING JAY...",Pasar Raya / Supermarket,Selangor,Petaling Jaya,3.075532,101.633965

In [47]:
dirty_eda_premises

,premise_code,premise,address,premise_type,state,district,latitude,longitude
0,-1,NaN,",",NaN,NaN,NaN,NaN,NaN
1,382,PASARAYA PKT PASIR TUMBOH,"G6582,LOT 11,KEDAI PASIR TUMBOH,",Pasar Raya / Supermarket,Kelantan,Kota Bharu,NaN,NaN
2,480,PASARAYA PANTAI TIMUR (BACHOK) SDN. BHD,"LOT 2076, MUKIM TEPUS,GUNUNG TIMUR,",Pasar Raya / Supermarket,Kelantan,Bachok,NaN,NaN
3,920,PASAR AWAM GEMAS,"NO. 1,PASAR BESAR GEMAS,",Pasar Basah,Negeri Sembilan,Gemas,NaN,NaN
4,1511,PASAR MINI BUDI,"NO. 24,KG. BUDI,",Pasar Mini,Kelantan,Bachok,NaN,NaN
...,...,...,...,...,...,...,...,...
56,20772,MARI-MARI SUPERMARKET,"NO 7,8 & 9, JALAN SRI MERSING 11,PUSAT PERDAGA...",Pasar Raya / Supermarket,Johor,Mersing,NaN,NaN
57,20819,KEDAI RUNCIT HJ. IBRAHIM,"NO 208,PTG. TOK MAHAT,",Kedai Runcit,Perak,Kerian,NaN,NaN
58,20820,79 FRESH MART SDN BHD,"LOT 2526,TAMAN ROD,",Kedai Runcit,Perak,Hilir Perak,NaN,NaN
59,20871,KITAI MART SDN BHD,"LOT 1273,SUBLOT 17-22,BLOCK 13,MENUAN LAND DIS...",Pasar Mini,Sarawak,Kapit,NaN,NaN
60,20874,CCK FRESH MART SDN BHD,"GROUND & 2ND FLOOR,LOT 248,SONG TOWN,GROUND & ...",Pasar Basah,Sarawak,Song,NaN,NaN

In [48]:
# Helper function to use pandasql
pysqldf = lambda q: sqldf(q, globals())

# Example query to find rows with missing data in the 'latitude' or 'latitude' column 
query = """
SELECT premise, address, state, district
FROM dirty_eda_premises
WHERE latitude OR longitude IS NULL
ORDER BY premise_code DESC;
"""

missing_data_df = pysqldf(query)
missing_data_df

,premise,address,state,district
0,CCK FRESH MART SDN BHD,"GROUND & 2ND FLOOR,LOT 248,SONG TOWN,GROUND & ...",Sarawak,Song
1,KITAI MART SDN BHD,"LOT 1273,SUBLOT 17-22,BLOCK 13,MENUAN LAND DIS...",Sarawak,Kapit
2,79 FRESH MART SDN BHD,"LOT 2526,TAMAN ROD,",Perak,Hilir Perak
3,KEDAI RUNCIT HJ. IBRAHIM,"NO 208,PTG. TOK MAHAT,",Perak,Kerian
4,MARI-MARI SUPERMARKET,"NO 7,8 & 9, JALAN SRI MERSING 11,PUSAT PERDAGA...",Johor,Mersing
...,...,...,...,...
56,PASAR MINI BUDI,"NO. 24,KG. BUDI,",Kelantan,Bachok
57,PASAR AWAM GEMAS,"NO. 1,PASAR BESAR GEMAS,",Negeri Sembilan,Gemas
58,PASARAYA PANTAI TIMUR (BACHOK) SDN. BHD,"LOT 2076, MUKIM TEPUS,GUNUNG TIMUR,",Kelantan,Bachok
59,PASARAYA PKT PASIR TUMBOH,"G6582,LOT 11,KEDAI PASIR TUMBOH,",Kelantan,Kota Bharu
60,None,",",None,None

In [19]:
# Select distinct values from 'address', 'state', and 'district' columns
distinct_missing_data_df = missing_data_df[['premise', 'address', 'state', 'district']].drop_duplicates()

# Print the result
distinct_missing_data_df

,premise,address,state,district
0,CCK FRESH MART SDN BHD,"GROUND & 2ND FLOOR,LOT 248,SONG TOWN,GROUND & ...",Sarawak,Song
1,KITAI MART SDN BHD,"LOT 1273,SUBLOT 17-22,BLOCK 13,MENUAN LAND DIS...",Sarawak,Kapit
2,79 FRESH MART SDN BHD,"LOT 2526,TAMAN ROD,",Perak,Hilir Perak
3,KEDAI RUNCIT HJ. IBRAHIM,"NO 208,PTG. TOK MAHAT,",Perak,Kerian
4,MARI-MARI SUPERMARKET,"NO 7,8 & 9, JALAN SRI MERSING 11,PUSAT PERDAGA...",Johor,Mersing
...,...,...,...,...
56,PASAR MINI BUDI,"NO. 24,KG. BUDI,",Kelantan,Bachok
57,PASAR AWAM GEMAS,"NO. 1,PASAR BESAR GEMAS,",Negeri Sembilan,Gemas
58,PASARAYA PANTAI TIMUR (BACHOK) SDN. BHD,"LOT 2076, MUKIM TEPUS,GUNUNG TIMUR,",Kelantan,Bachok
59,PASARAYA PKT PASIR TUMBOH,"G6582,LOT 11,KEDAI PASIR TUMBOH,",Kelantan,Kota Bharu
60,None,",",None,None

There is no duplicated address detected.

In [20]:
distinct_missing_data_df['validatedResult'] = ""

In [21]:
distinct_missing_data_df.head()

,premise,address,state,district,validatedResult
0,CCK FRESH MART SDN BHD,"GROUND & 2ND FLOOR,LOT 248,SONG TOWN,GROUND & ...",Sarawak,Song,
1,KITAI MART SDN BHD,"LOT 1273,SUBLOT 17-22,BLOCK 13,MENUAN LAND DIS...",Sarawak,Kapit,
2,79 FRESH MART SDN BHD,"LOT 2526,TAMAN ROD,",Perak,Hilir Perak,
3,KEDAI RUNCIT HJ. IBRAHIM,"NO 208,PTG. TOK MAHAT,",Perak,Kerian,
4,MARI-MARI SUPERMARKET,"NO 7,8 & 9, JALAN SRI MERSING 11,PUSAT PERDAGA...",Johor,Mersing,

In [30]:
import config

# Assuming df is your DataFrame loaded with data
# Google Maps API key
Google_Maps_API_KEY = config.Google_Maps_API_KEY  # to remove/replace this later on!! 

import requests

def validate_address(address, Google_Maps_API_KEY):
    # Define the endpoint URL
    url = "https://maps.googleapis.com/maps/api/place/findplacefromtext/json"

    # Define the parameters for the API request
    params = {
        'input': address,
        'inputtype': 'textquery',
        'fields': 'formatted_address,geometry',
        'key': Google_Maps_API_KEY
    }

    # Send the GET request to the API
    response = requests.get(url, params=params)

    # If the request was successful, return the data in JSON format
    if response.status_code == 200:
        return response.json()
    else:
        return None

In [31]:
# Create a new column in the DataFrame to store the validation results
distinct_missing_data_df['validatedResult'] = distinct_missing_data_df['address'].apply(lambda x: validate_address(x, Google_Maps_API_KEY))

# Print the DataFrame with validation results
print(distinct_missing_data_df)

                                    premise  \
0                    CCK FRESH MART SDN BHD
1                        KITAI MART SDN BHD
2                     79 FRESH MART SDN BHD
3                  KEDAI RUNCIT HJ. IBRAHIM
4                     MARI-MARI SUPERMARKET
..                                      ...
56                          PASAR MINI BUDI
57                         PASAR AWAM GEMAS
58  PASARAYA PANTAI TIMUR (BACHOK) SDN. BHD
59                PASARAYA PKT PASIR TUMBOH
60                                     None

                                              address            state  \
0   GROUND & 2ND FLOOR,LOT 248,SONG TOWN,GROUND & ...          Sarawak
1   LOT 1273,SUBLOT 17-22,BLOCK 13,MENUAN LAND DIS...          Sarawak
2                                 LOT 2526,TAMAN ROD,            Perak
3                             NO  208,PTG. TOK MAHAT,            Perak
4   NO 7,8 & 9, JALAN SRI MERSING 11,PUSAT PERDAGA...            Johor
..                                                ...              ...
56                                   NO. 24,KG. BUDI,         Kelantan
57                           NO. 1,PASAR BESAR GEMAS,  Negeri Sembilan
58                LOT 2076, MUKIM TEPUS,GUNUNG TIMUR,         Kelantan
59                   G6582,LOT 11,KEDAI PASIR TUMBOH,         Kelantan
60                                                  ,             None

       district                                    validatedResult
0          Song       {'candidates': [], 'status': 'ZERO_RESULTS'}
1         Kapit       {'candidates': [], 'status': 'ZERO_RESULTS'}
2   Hilir Perak       {'candidates': [], 'status': 'ZERO_RESULTS'}
3        Kerian       {'candidates': [], 'status': 'ZERO_RESULTS'}
4       Mersing  {'candidates': [{'formatted_address': '3A, 5, ...
..          ...                                                ...
56       Bachok       {'candidates': [], 'status': 'ZERO_RESULTS'}
57        Gemas  {'candidates': [{'formatted_address': '1930, 1...
58       Bachok       {'candidates': [], 'status': 'ZERO_RESULTS'}
59   Kota Bharu  {'candidates': [{'formatted_address': 'G6582, ...
60         None       {'candidates': [], 'status': 'ZERO_RESULTS'}

[61 rows x 5 columns]

In [32]:
distinct_missing_data_df

,premise,address,state,district,validatedResult
0,CCK FRESH MART SDN BHD,"GROUND & 2ND FLOOR,LOT 248,SONG TOWN,GROUND & ...",Sarawak,Song,"{'candidates': [], 'status': 'ZERO_RESULTS'}"
1,KITAI MART SDN BHD,"LOT 1273,SUBLOT 17-22,BLOCK 13,MENUAN LAND DIS...",Sarawak,Kapit,"{'candidates': [], 'status': 'ZERO_RESULTS'}"
2,79 FRESH MART SDN BHD,"LOT 2526,TAMAN ROD,",Perak,Hilir Perak,"{'candidates': [], 'status': 'ZERO_RESULTS'}"
3,KEDAI RUNCIT HJ. IBRAHIM,"NO 208,PTG. TOK MAHAT,",Perak,Kerian,"{'candidates': [], 'status': 'ZERO_RESULTS'}"
4,MARI-MARI SUPERMARKET,"NO 7,8 & 9, JALAN SRI MERSING 11,PUSAT PERDAGA...",Johor,Mersing,"{'candidates': [{'formatted_address': '3A, 5, ..."
...,...,...,...,...,...
56,PASAR MINI BUDI,"NO. 24,KG. BUDI,",Kelantan,Bachok,"{'candidates': [], 'status': 'ZERO_RESULTS'}"
57,PASAR AWAM GEMAS,"NO. 1,PASAR BESAR GEMAS,",Negeri Sembilan,Gemas,"{'candidates': [{'formatted_address': '1930, 1..."
58,PASARAYA PANTAI TIMUR (BACHOK) SDN. BHD,"LOT 2076, MUKIM TEPUS,GUNUNG TIMUR,",Kelantan,Bachok,"{'candidates': [], 'status': 'ZERO_RESULTS'}"
59,PASARAYA PKT PASIR TUMBOH,"G6582,LOT 11,KEDAI PASIR TUMBOH,",Kelantan,Kota Bharu,"{'candidates': [{'formatted_address': 'G6582, ..."
60,None,",",None,None,"{'candidates': [], 'status': 'ZERO_RESULTS'}"

In [53]:
import json

# Convert JSON objects in 'validatedResult' column to strings
distinct_missing_data_df['validatedResult'] = distinct_missing_data_df['validatedResult'].apply(json.dumps)

# SQL-like query using pandasql
query = """
SELECT address, state, district, validatedResult
FROM distinct_missing_data_df
WHERE validatedResult NOT LIKE '%ZERO_RESULTS%'
"""
filtered_df = sqldf(query, locals())

In [54]:
filtered_df

,address,state,district,validatedResult
0,"NO 7,8 & 9, JALAN SRI MERSING 11,PUSAT PERDAGA...",Johor,Mersing,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
1,"JALAN EMAS 4,PUSAT PERNIAGAAN KOTA EMAS,",Johor,Pontian,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
2,"PANTAI SELAMAT (PEKAN) FRESHCHOICE SDN. BHD., ...",Pahang,Pekan,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
3,"NO 1 JALAN BDJS 2, BLOK DAGANGAN JENGKA SEJAHT...",Pahang,Maran,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
4,"UNIT 4-10, BLOCK 2, GROUND FLOOR,LOT 640, JALA...",Sarawak,Kuching,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
5,"LOT S1,SECOND FLOOR, DARVEL BAY PLAZA,",Sabah,Lahad Datu,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
6,"SOOK,SOOK,",Sabah,Nabawan,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
7,"LOT 6,BLOK B,",Sabah,Tuaran,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
8,"D-G-19, GROUND FLOOR,JALAN METRO PERDANA 2,FOR...",W.P. Kuala Lumpur,Kepong,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
9,"NO.82, JALAN KAMPUNG BATU,BATU 5, JALAN IPOH,",W.P. Kuala Lumpur,Batu,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
10,"BANDAR SATELIT ISLAM,PASIR TUMBOH,",Kelantan,Kota Bharu,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
11,"KAWASAN LAZENDA,",W.P. Labuan,Kawasan Bandar,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
12,"PITAS,",Sabah,Pitas,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
13,"ADIKA COMMERCIAL COMPLEX,",Sabah,Keningau,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
14,"LOT 1032F,KG RHU MUDA,",Terengganu,Marang,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
15,"IR7/12- 1R12/16,MANMOHAN WAREHOUSE, JALAN PATA...",W.P. Labuan,Kawasan Luar Bandar,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
16,"LOT 347,KG WAKAF LANAS,",Kelantan,Pasir Puteh,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
17,"LOT PT5474-PT5488,JALAN LKS,",Kelantan,Kuala Krai,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
18,"PASAR KUBANG PASU,JALAN MASJID MUHAMMADI,",Kelantan,Kota Bharu,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
19,"MTTK 404/ 05,KG LALOH,",Kelantan,Kuala Krai,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
20,"NO.5, LOT 340 , KG. BAKAT,JALAN PASIR PUTEH,",Kelantan,Machang,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
21,PACIFIC FOOD COURTPACIFIC HYPERMARKET & DEPT S...,Kelantan,Kota Bharu,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
22,"BLOCK K, LOT 1,LORONG GRAND PLAZA PUTATAN,8820...",Sabah,Putatan,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
23,"LOT G 21, GROUND FLOOR, OCEANIC MALL,BATU 1/2 ...",Negeri Sembilan,Port Dickson,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
24,"LOT 335,BAU BAZAAR,",Sarawak,Bau,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
25,"LOT 558,DEPAN PEJABAT POS,",Kelantan,Tumpat,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
26,"NO. 1,PASAR BESAR GEMAS,",Negeri Sembilan,Gemas,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."
27,"G6582,LOT 11,KEDAI PASIR TUMBOH,",Kelantan,Kota Bharu,"""\""{\\\""candidates\\\"": [{\\\""formatted_addres..."

In [39]:
filtered_df['validatedResult']

0     "{\"candidates\": [{\"formatted_address\": \"3...
1     "{\"candidates\": [{\"formatted_address\": \"1...
2     "{\"candidates\": [{\"formatted_address\": \"L...
3     "{\"candidates\": [{\"formatted_address\": \"B...
4     "{\"candidates\": [{\"formatted_address\": \"J...
5     "{\"candidates\": [{\"formatted_address\": \"L...
6     "{\"candidates\": [{\"formatted_address\": \"9...
7     "{\"candidates\": [{\"formatted_address\": \"L...
8     "{\"candidates\": [{\"formatted_address\": \"1...
9     "{\"candidates\": [{\"formatted_address\": \"K...
10    "{\"candidates\": [{\"formatted_address\": \"2...
11    "{\"candidates\": [{\"formatted_address\": \"B...
12    "{\"candidates\": [{\"formatted_address\": \"P...
13    "{\"candidates\": [{\"formatted_address\": \"L...
14    "{\"candidates\": [{\"formatted_address\": \"K...
15    "{\"candidates\": [{\"formatted_address\": \"7...
16    "{\"candidates\": [{\"formatted_address\": \"L...
17    "{\"candidates\": [{\"formatted_address\": \"J...
18    "{\"candidates\": [{\"formatted_address\": \"D...
19    "{\"candidates\": [{\"formatted_address\": \"K...
20    "{\"candidates\": [{\"formatted_address\": \"J...
21    "{\"candidates\": [{\"formatted_address\": \"S...
22    "{\"candidates\": [{\"formatted_address\": \"B...
23    "{\"candidates\": [{\"formatted_address\": \"R...
24    "{\"candidates\": [{\"formatted_address\": \"9...
25    "{\"candidates\": [{\"formatted_address\": \"F...
26    "{\"candidates\": [{\"formatted_address\": \"1...
27    "{\"candidates\": [{\"formatted_address\": \"G...
Name: validatedResult, dtype: object

In [55]:
# The JSON string
json_data = "{\"candidates\": [{\"formatted_address\": \"3A, 5, 6, 7 ,8, 9, 10, 11, 12, JALAN SRI MERSING 3, Pusat Perdagangan Sri Mersing, 86800 Mersing, Johor, Malaysia\", \"geometry\": {\"location\": {\"lat\": 2.438656, \"lng\": 103.8327675}, \"viewport\": {\"northeast\": {\"lat\": 2.440006029892722, \"lng\": 103.8341252298927}, \"southwest\": {\"lat\": 2.437306370107278, \"lng\": 103.8314255701073}}}}], \"status\": \"OK\"}"

json_object = json.loads(json_data)
  
# Indent keyword while dumping the
# data decides to what level 
# spaces the user wants.
print(json.dumps(json_object, indent = 2))

{
  "candidates": [
    {
      "formatted_address": "3A, 5, 6, 7 ,8, 9, 10, 11, 12, JALAN SRI MERSING 3, Pusat Perdagangan Sri Mersing, 86800 Mersing, Johor, Malaysia",
      "geometry": {
        "location": {
          "lat": 2.438656,
          "lng": 103.8327675
        },
        "viewport": {
          "northeast": {
            "lat": 2.440006029892722,
            "lng": 103.8341252298927
          },
          "southwest": {
            "lat": 2.437306370107278,
            "lng": 103.8314255701073
          }
        }
      }
    }
  ],
  "status": "OK"
}

In [56]:
# Define a function to parse JSON and extract formatted_address
def extract_formatted_address(json_str):
    data = json.loads(json_str)
    if 'candidates' in data and data['candidates']:
        return data['candidates'][0]['formatted_address']
    return None

# Define a function to parse JSON and extract latitude
def extract_latitude(json_str):
    data = json.loads(json_str)
    if 'candidates' in data and data['candidates']:
        return data['candidates'][0]['geometry']['location']['lat']
    return None

# Define a function to parse JSON and extract longitude
def extract_longitude(json_str):
    data = json.loads(json_str)
    if 'candidates' in data and data['candidates']:
        return data['candidates'][0]['geometry']['location']['lng']
    return None

# Apply the functions to the 'validatedResult' column to create new columns
filtered_df['formatted_address'] = filtered_df['validatedResult'].apply(extract_formatted_address)
filtered_df['latitude'] = filtered_df['validatedResult'].apply(extract_latitude)
filtered_df['longitude'] = filtered_df['validatedResult'].apply(extract_longitude)

TypeError: string indices must be integers, not 'str'

In [ ]:
import requests
import pandas as pd

# Load your dataframe
df = pd.read_csv('path_to_your_file.csv')  # make sure to use your actual file path

# Function to call Google Maps API for address validation
def validate_address(address, api_key):
    url = "https://maps.googleapis.com/maps/api/place/findplacefromtext/json"
    params = {
        'input': address,
        'inputtype': 'textquery',
        'fields': 'formatted_address,geometry',
        'key': api_key
    }
    response = requests.get(url, params=params)
    if response.status_code == 200:
        return response.json()
    else:
        return None

# API Key (Make sure to replace 'YOUR_API_KEY' with your actual Google Maps API key)
api_key = 'YOUR_API_KEY'

# Validate addresses and store results
results = []
for address in df['normalized_address']:
    result = validate_address(address, api_key)
    results.append(result)

# You might want to add results to your dataframe or handle them differently based on your needs
df['validation_results'] = results

# Save or display the dataframe
print(df.head())

In [ ]:
# Google Maps API key
google_maps_api_key = config.Google_Maps_API_KEY  # to remove/replace this later on!! 
df = distinct_missing_data_df

def fetch_coordinates(api_key, address):
    """Fetch coordinates (latitude, longitude) for the given address using Google Maps Geocoding API."""
    base_url = "https://maps.googleapis.com/maps/api/geocode/json"
    response = requests.get(base_url, params={'address': address, 'region': 'Malaysia', 'key': google_maps_api_key})
    if response.status_code == 200:
        data = response.json()
        if data['results']:
            latitude = data['results'][0]['geometry']['location']['lat']
            longitude = data['results'][0]['geometry']['location']['lng']
            return latitude, longitude
    return None, None

# Loop through the DataFrame and update with coordinates
for index, row in df.iterrows():
    if row['address'].strip():  # Skip empty addresses
        lat, lon = fetch_coordinates(api_key, row['address'])
        df.at[index, 'latitude'] = lat
        df.at[index, 'longitude'] = lon
        
    if (index + 1) % 500 == 0:  # Print update every 500 rows
        print(f"Updated {index + 1} rows with coordinates.")

# Final update status
print(f"Finished updating coordinates for all rows.")

# Optionally, print or inspect the first few rows to check updates
print(df.head())

In [ ]:
import requests
import urllib.parse

def geocode_address(google_maps_api_key, address, region='my'):
    # Format the address
    encoded_address = urllib.parse.quote(address)

    # Construct the Geocoding API request
    api_url = f"https://maps.googleapis.com/maps/api/geocode/json?address={encoded_address}&key={api_key}&region={region}"

    # Send the request
    response = requests.get(api_url)

    # Parse the response
    if response.status_code == 200:
        data = response.json()

        # Check if the request was successful
        if data['status'] == 'OK':
            # Handle ambiguous results by either choosing the first result or prompting the user
            results = data['results']
            if 'partial_match' in results[0]:
                print("Warning: The address may be incomplete or ambiguous.")
            return results
        else:
            print(f"Geocoding failed with status: {data['status']}")
            return None
    else:
        print(f"Request failed with status code: {response.status_code}")
        return None

# Example usage
api_key = 'YOUR_API_KEY'
address = 'Ambiguous Address Here'
geocoded_results = geocode_address(api_key, address)

# Processing the results as needed for your application
# ...

In [ ]:
# Standardize common address abbreviations
standardization_dict = {
    'St\.?': 'Street',
    'Rd\.?': 'Road',
    'Ave\.?': 'Avenue',
    'Dr\.?': 'Drive',
    'Ln\.?': 'Lane',
    'Blvd\.?': 'Boulevard',
    'Ct\.?': 'Court',
    'Pl\.?': 'Place'
}

# Apply the standardization to the 'address' column
address_data['address'] = address_data['address'].replace(standardization_dict, regex=True)

# Concatenate address components into a full address column
address_data['full_address'] = address_data['address'].astype(str) + ', ' + \
                               address_data['district'] + ', ' + \
                               address_data['state']

# Remove any rows where the address is NaN (previously set to <NA> which becomes 'nan' when converted to string)
address_data = address_data[address_data['address'].notna()]

# Show changes
address_data[['full_address']].head()